// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa5IBFygnjEMljkLP4G1JbhOdhCvpyVnw',
    appId: '1:451425538316:web:800847919139d532a8f929',
    messagingSenderId: '451425538316',
    projectId: 'gestao-scrum-gft',
    authDomain: 'gestao-scrum-gft.firebaseapp.com',
    storageBucket: 'gestao-scrum-gft.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTnbraFZKd7z7nSdDPWRBhXvHmq8PwBwY',
    appId: '1:451425538316:android:4c752a327ad18fa5a8f929',
    messagingSenderId: '451425538316',
    projectId: 'gestao-scrum-gft',
    storageBucket: 'gestao-scrum-gft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMjEjy6FidvWL2CkXycqc79WAC5eYKrs',
    appId: '1:451425538316:ios:cbb1b1972b7d152ea8f929',
    messagingSenderId: '451425538316',
    projectId: 'gestao-scrum-gft',
    storageBucket: 'gestao-scrum-gft.appspot.com',
    iosClientId: '451425538316-cpe59j9frjn17pnbol3a4josh8pp6joq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestaoScrumGft',
  );
}
